### ISSUE TITLE
Cant Make Harry Invisible Help me 

### ISSUE THREAD

**Issue by wolf192002** [joonspoon/madecraft-oop#2]
![inv](https://user-images.githubusercontent.com/90395297/137260606-90164c42-16e4-47cf-8a91-e6403718a423.png)

**Comment by joonspoon** [comment]
Hey there Wolf,

Compiler errors can be a bit cryptic at first, but you'll need to get used to making sense of them.
The writing in red is trying to tell you that "no arguments" were found where a "boolean" was required. 
Compare how you are using makeInvisible() to how it is described in the Harry class.
Can you spot the problem?
Good luck, and keep me posted :)

June.
